name: Build Quickstart Image

on:
  push:
    branches:
      - main

jobs:
  build-stellar-friendbot:
    runs-on: ubuntu-latest
    steps:
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Stellar-Friendbot Image
        run: >
          docker buildx build --platform linux/amd64
          -f services/friendbot/docker/Dockerfile -t stellar-friendbot:amd64
          -o type=docker,dest=/tmp/image 
          --build-arg BUILDKIT_CONTEXT_KEEP_GIT_DIR=true 
          https://github.com/stellar/go.git#release-horizon-v2.25.0
      - name: Upload Stellar-Friendbot Image
        uses: actions/upload-artifact@v4
        with:
          name: image-stellar-friendbot-amd64
          path: /tmp/image

  build-quickstart:
    needs: [build-stellar-friendbot]
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Stellar-Friendbot Image
        uses: actions/download-artifact@v4
        with:
          name: image-stellar-friendbot-amd64
          path: /tmp/stellar-friendbot
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      - name: Load Stellar-Friendbot Image
        run: docker load -i /tmp/stellar-friendbot/image
      - name: Pull Base Image
        run: docker pull --platform linux/amd64 ubuntu:22.04
      # Docker buildx cannot be used to build the dev quickstart image because
      # buildx does not yet support importing existing images, like the core and
      # horizon images above, into a buildx builder's cache. Buildx would be
      # preferred because it can output a smaller image file faster than docker
      # save can.  Once buildx supports it we can update.
      # https://github.com/docker/buildx/issues/847
      - name: Build Quickstart Image
        run: >
          docker build
          --platform linux/amd64
          -f Dockerfile
          -t ghcr.io/xdbfoundation/xdbchain-quickstart:latest
          .
          --build-arg STELLAR_CORE_VERSION=19.8.0-1227.040a29c51.jammy
          --build-arg HORIZON_VERSION=2.25.0-343
          --build-arg FRIENDBOT_IMAGE_REF=stellar-friendbot:amd64
      - name: Publish Quickstart Image
        run: docker push ghcr.io/xdbfoundation/xdbchain-quickstart:latest

          